#!/bin/bash
# ClaudeKit Codebase Map Generator
# Generates structured codebase overview for Claude context

OUTPUT_PATH="${1:-.claude/CODEBASE_MAP.md}"
PROJECT_ROOT="${2:-.}"
DEPTH="${3:-3}"

get_project_type() {
    local root="$1"
    local types=""

    [ -f "$root/package.json" ] && types="${types}node, "
    [ -f "$root/requirements.txt" ] || [ -f "$root/pyproject.toml" ] && types="${types}python, "
    [ -f "$root/Cargo.toml" ] && types="${types}rust, "
    [ -f "$root/go.mod" ] && types="${types}go, "
    ls "$root"/*.sln 2>/dev/null && types="${types}dotnet, "

    echo "${types%, }"
}

get_directory_tree() {
    local path="$1"
    local depth="${2:-3}"

    find "$path" -maxdepth "$depth" -type d \
        -not -path '*/node_modules/*' \
        -not -path '*/.git/*' \
        -not -path '*/__pycache__/*' \
        -not -path '*/.next/*' \
        -not -path '*/dist/*' \
        -not -path '*/build/*' \
        -not -path '*/.venv/*' \
        -not -path '*/venv/*' \
        -not -name 'node_modules' \
        -not -name '.git' \
        2>/dev/null | head -100 | sed 's|[^/]*/|  |g'
}

get_file_stats() {
    local root="$1"

    echo "| Extension | Files | Lines |"
    echo "|-----------|-------|-------|"

    find "$root" -type f \
        -not -path '*/node_modules/*' \
        -not -path '*/.git/*' \
        -not -path '*/__pycache__/*' \
        2>/dev/null | \
    sed 's/.*\.//' | sort | uniq -c | sort -rn | head -10 | \
    while read count ext; do
        lines=$(find "$root" -name "*.$ext" \
            -not -path '*/node_modules/*' \
            -not -path '*/.git/*' \
            -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
        echo "| .$ext | $count | ${lines:-0} |"
    done
}

get_key_directories() {
    local root="$1"

    declare -A patterns
    patterns=(
        ["src"]="Source code"
        ["lib"]="Library code"
        ["app"]="Application"
        ["pages"]="Pages"
        ["components"]="UI Components"
        ["api"]="API routes"
        ["services"]="Services layer"
        ["utils"]="Utilities"
        ["hooks"]="React hooks"
        ["models"]="Data models"
        ["tests"]="Tests"
        ["docs"]="Documentation"
    )

    for dir in "${!patterns[@]}"; do
        if [ -d "$root/$dir" ]; then
            count=$(find "$root/$dir" -type f -not -path '*/node_modules/*' 2>/dev/null | wc -l)
            echo "- **$dir/**: ${patterns[$dir]} ($count files)"
        fi
    done
}

get_entry_points() {
    local root="$1"

    if [ -f "$root/package.json" ]; then
        main=$(grep -o '"main"[[:space:]]*:[[:space:]]*"[^"]*"' "$root/package.json" | cut -d'"' -f4)
        [ -n "$main" ] && echo "- Main: $main"
    fi

    for entry in src/index.ts src/index.js src/main.ts main.py app.py index.ts index.js; do
        if [ -f "$root/$entry" ]; then
            echo "- Entry: $entry"
            break
        fi
    done
}

# Main execution
ROOT=$(cd "$PROJECT_ROOT" && pwd)
PROJECT_NAME=$(basename "$ROOT")
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

# Ensure output directory exists
OUTPUT_DIR=$(dirname "$OUTPUT_PATH")
[ -n "$OUTPUT_DIR" ] && [ "$OUTPUT_DIR" != "." ] && mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT_PATH" << EOF
# Codebase Map: $PROJECT_NAME

> Generated: $TIMESTAMP
> Project Type: $(get_project_type "$ROOT")

## Directory Structure

\`\`\`
$(get_directory_tree "$ROOT" "$DEPTH")
\`\`\`

## Key Directories

$(get_key_directories "$ROOT")

## Entry Points

$(get_entry_points "$ROOT")

## File Statistics

$(get_file_stats "$ROOT")

---
*Generated by ClaudeKit Codebase Map | Use with caution - may be outdated*
EOF

echo "[CODEBASE MAP] Generated: $OUTPUT_PATH"
